// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basketball.proto

package basketBallPlayer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,5,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	PointsPerGame        int32    `protobuf:"varint,6,opt,name=points_per_game,json=pointsPerGame,proto3" json:"points_per_game,omitempty"`
	AssistsPerGame       int32    `protobuf:"varint,7,opt,name=assists_per_game,json=assistsPerGame,proto3" json:"assists_per_game,omitempty"`
	ReboundsPerGame      int32    `protobuf:"varint,8,opt,name=rebounds_per_game,json=reboundsPerGame,proto3" json:"rebounds_per_game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_c114fefff092adb9, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Player) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Player) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Player) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *Player) GetPointsPerGame() int32 {
	if m != nil {
		return m.PointsPerGame
	}
	return 0
}

func (m *Player) GetAssistsPerGame() int32 {
	if m != nil {
		return m.AssistsPerGame
	}
	return 0
}

func (m *Player) GetReboundsPerGame() int32 {
	if m != nil {
		return m.ReboundsPerGame
	}
	return 0
}

type PlayerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRequest) Reset()         { *m = PlayerRequest{} }
func (m *PlayerRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerRequest) ProtoMessage()    {}
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c114fefff092adb9, []int{1}
}

func (m *PlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRequest.Unmarshal(m, b)
}
func (m *PlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRequest.Marshal(b, m, deterministic)
}
func (m *PlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRequest.Merge(m, src)
}
func (m *PlayerRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerRequest.Size(m)
}
func (m *PlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRequest proto.InternalMessageInfo

func (m *PlayerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PlayerResponse struct {
	Result               *Player  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerResponse) Reset()         { *m = PlayerResponse{} }
func (m *PlayerResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerResponse) ProtoMessage()    {}
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c114fefff092adb9, []int{2}
}

func (m *PlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerResponse.Unmarshal(m, b)
}
func (m *PlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerResponse.Marshal(b, m, deterministic)
}
func (m *PlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerResponse.Merge(m, src)
}
func (m *PlayerResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerResponse.Size(m)
}
func (m *PlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerResponse proto.InternalMessageInfo

func (m *PlayerResponse) GetResult() *Player {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "basketBallPlayer.Player")
	proto.RegisterType((*PlayerRequest)(nil), "basketBallPlayer.PlayerRequest")
	proto.RegisterType((*PlayerResponse)(nil), "basketBallPlayer.PlayerResponse")
}

func init() { proto.RegisterFile("basketball.proto", fileDescriptor_c114fefff092adb9) }

var fileDescriptor_c114fefff092adb9 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x9f, 0xa6, 0x4f, 0x63, 0x3b, 0xd2, 0x17, 0xd7, 0x4b, 0x50, 0xa4, 0x21, 0x07, 0x09,
	0x1e, 0x82, 0xd4, 0x6f, 0xd0, 0x4b, 0x6f, 0x52, 0x22, 0x5e, 0xbc, 0x84, 0x8d, 0x19, 0xeb, 0xd2,
	0x6d, 0x36, 0xee, 0x6e, 0x04, 0x8f, 0x7e, 0x73, 0xd9, 0x37, 0x28, 0x85, 0xde, 0x96, 0xdf, 0xff,
	0x37, 0xb3, 0xc3, 0x0c, 0x2c, 0x6a, 0xaa, 0xf6, 0xa8, 0x6b, 0xca, 0x79, 0xd1, 0x49, 0xa1, 0x05,
	0xf1, 0x64, 0x4d, 0x39, 0xdf, 0x72, 0xfa, 0x83, 0x32, 0xfb, 0x8d, 0x20, 0x76, 0x4f, 0x32, 0x83,
	0x88, 0x35, 0xc9, 0x20, 0x1d, 0xe4, 0x93, 0x32, 0x62, 0x0d, 0xb9, 0x03, 0xf8, 0x60, 0x52, 0xe9,
	0xaa, 0xa5, 0x07, 0x4c, 0x22, 0xcb, 0x27, 0x96, 0x3c, 0xd3, 0x03, 0x92, 0x5b, 0x98, 0x70, 0x1a,
	0xd2, 0xa1, 0x4d, 0xc7, 0x06, 0xd8, 0x70, 0x01, 0x43, 0xba, 0xc3, 0xe4, 0x7f, 0x3a, 0xc8, 0x47,
	0xa5, 0x79, 0x1a, 0xbd, 0xfb, 0x14, 0x5a, 0x54, 0xbd, 0xe4, 0xc9, 0xc8, 0xe9, 0x16, 0xbc, 0x4a,
	0x4e, 0xee, 0x61, 0xde, 0x09, 0xd6, 0x6a, 0x55, 0x75, 0x28, 0xab, 0x9d, 0xe9, 0x18, 0xdb, 0xd2,
	0xa9, 0xc3, 0x5b, 0x94, 0x1b, 0xd3, 0x36, 0x87, 0x05, 0x55, 0x8a, 0xa9, 0x63, 0xf1, 0xc2, 0x8a,
	0x33, 0xcf, 0x83, 0xf9, 0x00, 0x57, 0x12, 0x6b, 0xd1, 0xb7, 0xcd, 0x91, 0x3a, 0xb6, 0xea, 0x3c,
	0x04, 0xde, 0xcd, 0x96, 0x30, 0x75, 0x2b, 0x28, 0xf1, 0xab, 0x47, 0xa5, 0x4f, 0x37, 0x91, 0xad,
	0x61, 0x16, 0x04, 0xd5, 0x89, 0x56, 0x21, 0x79, 0x84, 0x58, 0xa2, 0xea, 0xb9, 0xb6, 0xd6, 0xe5,
	0x2a, 0x29, 0x4e, 0x37, 0x5b, 0xf8, 0x0a, 0xef, 0xad, 0xf6, 0xe1, 0x93, 0x17, 0x94, 0xdf, 0xec,
	0x1d, 0xc9, 0x1b, 0x5c, 0x6f, 0x4c, 0x41, 0x38, 0x91, 0xbf, 0xc2, 0xf2, 0x6c, 0x27, 0x37, 0xdc,
	0x4d, 0x7a, 0x5e, 0x70, 0xc3, 0x65, 0xff, 0xea, 0xd8, 0x9e, 0xfb, 0xe9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x0d, 0x64, 0x25, 0x15, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerServiceClient interface {
	GetBasketballPlayer(ctx context.Context, in *PlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error)
}

type playerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayerServiceClient(cc *grpc.ClientConn) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) GetBasketballPlayer(ctx context.Context, in *PlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error) {
	out := new(PlayerResponse)
	err := c.cc.Invoke(ctx, "/basketBallPlayer.PlayerService/GetBasketballPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
type PlayerServiceServer interface {
	GetBasketballPlayer(context.Context, *PlayerRequest) (*PlayerResponse, error)
}

// UnimplementedPlayerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServiceServer struct {
}

func (*UnimplementedPlayerServiceServer) GetBasketballPlayer(ctx context.Context, req *PlayerRequest) (*PlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasketballPlayer not implemented")
}

func RegisterPlayerServiceServer(s *grpc.Server, srv PlayerServiceServer) {
	s.RegisterService(&_PlayerService_serviceDesc, srv)
}

func _PlayerService_GetBasketballPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetBasketballPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basketBallPlayer.PlayerService/GetBasketballPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetBasketballPlayer(ctx, req.(*PlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basketBallPlayer.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBasketballPlayer",
			Handler:    _PlayerService_GetBasketballPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basketball.proto",
}
